### ISSUE TITLE
Current version CUTE (v0.1.0) does not work with github.com/ozontech/allure-go@v0.6.11

### ISSUE THREAD

**Issue by ChebaKuvaldos** [ozontech/cute#12]
Test launch crushed:
../../../go/pkg/mod/github.com/ozontech/cute@v0.1.0/test.go:114:22: too many arguments in call to common.NewT
        have (*testing.T, string, string)
        want (provider.TestingT)

**Comment by siller174** [comment]
Implemented in https://github.com/ozontech/cute/releases/tag/v0.1.3
