### ISSUE TITLE
problem with ExpectJSONSchemaFile

### ISSUE THREAD

**Issue by ermek-** [ozontech/cute#40]
reproduction steps:
1. create json local file, example:
`{
   "name" : "Elton",
   "adult" : true
}`
2. use ExpectJSONSchemaFile in my test
3. in response has json like this:
`{
   "name" : "Ivan",
   "adult" : false
}`

expected result:
my test will have a fallen status, because name ≠ Elton and adult ≠ true

actual result:
my test is passed

If ExpectJSONSchemaFile only validate response by json schema, but not checking value, please add something like this for check json character by character

**Comment by alex-ello** [comment]
Your JSON schema should look like this:

```json
{
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "const":"Elton",
    },
      "adult": {
        "type":"boolean",
      }
  },
  "required": [
    "name",
    "adult"
  ]
}
```

**Comment by nugolnikova** [comment]
Hi, ermek-!
ExpectJSONSchemaFile only validate response by json schema, not checking value, it is expected behavior.
If you want to check value, please use json.Equal/json.NotEqual functions https://github.com/ozontech/cute/blob/master/asserts/json/json.go
