### ISSUE TITLE
Can't read json_path syntax in AssertBody

### ISSUE THREAD

**Issue by ChebaKuvaldos** [ozontech/cute#41]
code:
`OptionalAssertBody(
		json.Equal("$.entries[?(@.role == 'HR-партнер')].event", "Анкета согласована"),
	).`
error:		
`test.go:178: [OPTIONAL ERROR] evaluating '$.entries[?(@.role == 'Сторонняя система проверки СБ')].event' resulted in error: 'parsing error: $.entries[?(@.role == 'Сторонняя система проверки СБ')].event	:1:23 - 1:54 could not parse string: invalid syntax'`

This syntax is corresponds to the library [JsonPath](https://github.com/json-path/JsonPath#:~:text=%24..book%5B%3F(%40.author%20%3D~%20/.*REES/i)%5D), but using this in 0.1.8 make error

**Comment by siller174** [comment]
Implemented in https://github.com/ozontech/cute/pull/48

**Comment by siller174** [comment]
fixed in https://github.com/ozontech/cute/releases/tag/v0.1.12
