### ISSUE TITLE
Suggestion to correct mistakes in "about" section 

### ISSUE THREAD

**Issue by ktitaro** [ozontech/cute#5]
Hey, fellow ozon developers 👋
I suggest, you may update the text of "about" section of this repository and correct mistakes in the use of English:

```Library for simply creates HTTP tests in Go with Allure reports.``` ->
```Library for simply creating HTTP tests in Go with Allure reports.```

It would be much better English 🙂
Cheers ✌️

**Comment by siller174** [comment]
Yes, it's my mistake. Thank you!
