### ISSUE TITLE
 Fix cuteErrors.NewAssertError function

### ISSUE THREAD

**Issue by ekattitova98** [ozontech/cute#63]
Прошу исправить функцию `cuteErrors.NewAssertError`

сейчас если передавать параметры `actual `interface{} и `expected` interface{}, то в ответе они не возвращаются (и в результате теста тоже) 

пример:
<img width="681" alt="image" src="https://github.com/ozontech/cute/assets/117189875/1b3815de-e625-4f22-ba9e-ae5e02111cd0">

**Comment by siller174** [comment]
fixed in https://github.com/ozontech/cute/pull/69
