### ISSUE TITLE
Possibility to not fail the test during retries

### ISSUE THREAD

**Issue by samybenatt** [ozontech/cute#70]
https://github.com/ozontech/cute/blob/9389b6037620bc4f0452f92df3fb16d46eda9deb/roundtripper.go#L103-L108

Would it be possible to have a way to configure this part to return optional error.

For example, here:
https://github.com/ozontech/cute/blob/9389b6037620bc4f0452f92df3fb16d46eda9deb/test.go#L56-L58
```go
type RequestRepeatPolitic struct {
        Count int
        OptionalError bool
        Delay time.Duration
}
```
Add an OptionalError bool that, if defined to `true`, will return `cuteErrors.NewOptionalError` instead of `cuteErrors.NewAssertError`
If the count has reached its last index, then switch back `cuteErrors.NewAssertError` and ultimately fail the test

**Comment by siller174** [comment]
Hello.
It's possible. I think, I will do it together with https://github.com/ozontech/cute/issues/64

**Comment by siller174** [comment]
Or you can do it as you described.

**Comment by samybenatt** [comment]
> Or you can do it as you described.

Sure, I just wanted to validate the approach with you first, let me create a pull request!

**Comment by samybenatt** [comment]
@siller174 https://github.com/ozontech/cute/pull/71
Here is the PR

**Comment by siller174** [comment]
Thank you! I will check PR

**Comment by siller174** [comment]
@samybenatt Sorry for the delay. Could you please review my implementation for your request?
https://github.com/ozontech/cute/pull/72/files

**Comment by samybenatt** [comment]
> @samybenatt Sorry for the delay. Could you please review my implementation for your request? https://github.com/ozontech/cute/pull/72/files

Hi @siller174, thanks for taking time to implement this! I've sent very minor comments on the PR but overall lgtm!

**Comment by siller174** [comment]
Thank you again! Released https://github.com/ozontech/cute/releases/tag/v0.1.20

**Comment by samybenatt** [comment]
@siller174 Based on my latest comment I think I wrongly understood your implementation

I think there is still one thing missing:
- If Optional: true and all retries are failing: then mark the whole test as failing, else mark the test as success

Basically, in pseudo-code:
if currentTryCount < RequestPoliticRetryCount and retry.status = success:
  test.status = success
else:
  test.status = failure

**Comment by samybenatt** [comment]
@siller174 
https://github.com/ozontech/cute/pull/72#discussion_r1589163201
To complete the above comment in the PR

Here is a concrete example:
```go
import (
	"context"
	"github.com/ozontech/cute/asserts/headers"
	"net/http"
	"testing"

	"github.com/ozontech/cute"
)

func Test_Table_Array(t *testing.T) {
	tests := []*cute.Test{
		{
			Name: "test_1",
			Request: &cute.Request{
				Repeat: &cute.RequestRepeatPolitic{Count: 4, Optional: true},
				Builders: []cute.RequestBuilder{
					cute.WithURI("https://httpstat.us/Random/203,200,201"),
					cute.WithMethod(http.MethodGet),
				},
			},
			Expect: &cute.Expect{
				Code:          200,
				AssertHeaders: []cute.AssertHeaders{headers.Present("Content-Type")},
			},
		},
		{
			Name:       "test_2",
			Middleware: nil,
			Request: &cute.Request{
				Repeat: &cute.RequestRepeatPolitic{Count: 2, Optional: true},
				Builders: []cute.RequestBuilder{
					cute.WithURI("https://httpstat.us/Random/201,202"),
					cute.WithMethod(http.MethodGet),
				},
			},
			Expect: &cute.Expect{
				Code: 200,
			},
		},
	}

	cute.NewTestBuilder().
		Title("Example table test").
		Tag("table_test").
		Description("Execute array tests").
		CreateTableTest().
		PutTests(tests...).
		ExecuteTest(context.Background(), t)
}

```

The above example tests will be:
- test_1 -> random HTTP code between 200/201/203
- test_2 -> random HTTP code between 201/202 (never 200)

Here is the result in the allure report and in the test run:
![image](https://github.com/ozontech/cute/assets/24391573/812d3eae-3047-4465-9b82-f10bc5ea71a8)

And in the allure report:
![image](https://github.com/ozontech/cute/assets/24391573/633523dd-8f29-41f4-8c27-73a0f3acf0ef)
![image](https://github.com/ozontech/cute/assets/24391573/c898d162-2a1d-48a6-9a90-e2ec10f4eda2)


As you can see, for the test_1, my assert header is never executed while one of the retry was successful
For the test_2, the whole test is marked as success while all the retries fail up to the last retry
