### ISSUE TITLE
Proper timeout logging and handling

### ISSUE THREAD

**Issue by samybenatt** [ozontech/cute#80]
Currently, when request is timing out because of deadline exceeded, the logging is not very clear:
![image](https://github.com/ozontech/cute/assets/24391573/8703b3b4-6c1f-4ea8-ad6e-51112980a0de)

With the PR https://github.com/ozontech/cute/pull/79 , here is the result:
![image](https://github.com/ozontech/cute/assets/24391573/14154f73-06b4-4ea8-901c-8438eb90bb24)

**Comment by siller174** [comment]
resolved in v0.1.22
